// <auto-generated />
using System;
using MemoryCards.Persistance.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoryCards.Persistance.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230508223457_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("MemoryCards.Persistance.Models.GameCommonSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvialableLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameCommonSettingses");
                });
#pragma warning restore 612, 618
        }
    }
}
